### ISSUE TITLE
Feature: Provide MCS API-conformant ServiceImport interface while preserving KubeSlice’s richer ServiceImport

### ISSUE THREAD

**Issue by kahirokunn** [kubeslice/kubeslice#55]
### 🔖 Feature description

Currently, **KubeSlice** has a custom `ServiceImport` resource that provides more data than the standard [Multi-Cluster Services (MCS) API](https://github.com/kubernetes-sigs/mcs-api). While that extra information is beneficial for KubeSlice’s functionality, there is a growing need to also expose a **standard MCS API-conformant `ServiceImport`** for interoperability with:

- [Gateway API](https://gateway-api.sigs.k8s.io/) implementations that allow `ServiceImport` as a backend in `HTTPRoute`.
- Other tooling (e.g., [Cilium](https://github.com/cilium/cilium/releases/tag/v1.17.0)) that expects MCS-compliant resources.

Instead of replacing KubeSlice’s existing `ServiceImport`, we propose **maintaining the richer KubeSlice `ServiceImport`** while **translating** it into a standard MCS API `ServiceImport` for compatibility. This approach provides the best of both worlds:

1. **Preserves** the extra, KubeSlice-specific functionality.
2. **Enables** a user experience consistent with the standard MCS specification for third-party integrations.

### 🎤 Pitch

- **Growing MCS adoption**: Many projects and controllers now rely on the standard MCS API. By offering an MCS-conformant interface, KubeSlice can integrate seamlessly with them.
- **Gateway API backends**: Gateway routes (e.g., `HTTPRoute`) increasingly support referencing a standard `ServiceImport`. A standard interface from KubeSlice would open the door for direct usage of KubeSlice services in these routes.
- **Broader ecosystem support**: Tools like Cilium and others provide features around MCS-compliant resources. KubeSlice users can leverage these immediately if a conformant resource is exposed.

Below is an example where `HTTPRoute` references a `ServiceImport`:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
  namespace: default
spec:
  parentRefs:
    - name: eg
  hostnames:
    - "www.example.com"
  rules:
    - backendRefs:
        - group: multicluster.x-k8s.io
          kind: ServiceImport
          name: backend-default-cluster2
          namespace: submariner-operator
          port: 3000
      matches:
        - path:
            type: PathPrefix
            value: /
```

If KubeSlice provided an MCS-conformant `ServiceImport`, the `HTTPRoute` (and other future integrations) could consume multi-cluster KubeSlice services natively.

### ✌️ Solution

1. **Maintain KubeSlice’s enriched `ServiceImport`:**
   - Continue to store and manage data as is, ensuring no break in existing features or workflows.

2. **Expose a translated MCS API `ServiceImport` resource:**
   - Create a new mechanism to **reflect** KubeSlice’s enriched `ServiceImport` in the standard MCS format.  
   - This could be done via:
     - A **controller** or operator that watches for changes to the KubeSlice `ServiceImport` CR and updates/creates a corresponding MCS-conformant `ServiceImport`.
     - A **conversion webhook** or translation layer that presents the MCS-compliant subset of data while keeping the additional KubeSlice details in the background.

3. **Synchronize status and endpoints (`EndpointSlice`):**
   - In addition to `ServiceImport`, also provide or translate relevant `EndpointSlice` data to fully comply with the MCS spec.  
   - This ensures that any third-party controllers relying on standard MCS `EndpointSlice` data can discover and route traffic properly.

This approach allows KubeSlice to keep its rich feature set while also **opening doors** to all the ecosystem tools that expect MCS API-conformant resources.

### 🔄️ Alternative

- **Replacing** the existing KubeSlice `ServiceImport` with the standard MCS `ServiceImport` would lose the additional KubeSlice-specific functionality or require adding complex custom fields within the MCS resource.
- **Maintaining only KubeSlice’s resource** and ignoring MCS standardization means missing out on broader Gateway API and third-party tool compatibility.

Hence, **a side-by-side approach with translation** is more flexible and future-proof.

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/kubeslice/kubeslice/blob/master/code_of_conduct.md)
